// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyrimDescriber;

#nullable disable

namespace skyrim_describer.Migrations
{
    [DbContext(typeof(SkyrimDescriberContext))]
    partial class SkyrimDescriberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("SkyrimDescriber.Location", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("SkyrimDescriber.Npc", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("LocationName");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("SkyrimDescriber.Npc", b =>
                {
                    b.HasOne("SkyrimDescriber.Location", null)
                        .WithMany("Npcs")
                        .HasForeignKey("LocationName");
                });

            modelBuilder.Entity("SkyrimDescriber.Location", b =>
                {
                    b.Navigation("Npcs");
                });
#pragma warning restore 612, 618
        }
    }
}
